In [1]:
import numpy as np

# Slicing and Indexing

## Field Access dan Basic Indexing

In [2]:
# contoh 1 index tunggal, field index
a = np.arange(10) 
print(a)
b = a[5] 
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [3]:
# Contoh 2
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [4]:
#contoh 3
a = np.arange(10) 
b = a[2:7:2] 
print(b)

[2 4 6]


In [5]:
#contoh 4 slicing index hanya dengan menggunakan parameter start
a = np.arange(10) 
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [6]:
#contoh 5 slicing menggunakan start dan stop index
a = np.arange(10) 
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [7]:
#contoh 6 slicing pada array dua dimensi
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)

# slice items starting from index
print('slice array dari index a[1:]') 
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
slice array dari index a[1:]
[[3 4 5]
 [4 5 6]]


In [8]:
#contoh 7 menggunakan ellipsis (...)
a = np.array([[1,2,3],
              [3,4,5],
              [4,5,6]]) 

print('Array kita:') 
print(a) 
print('\n')  

# ini mengembalikan item di kolom kedua dari array utama 
print('item dari kolom kedua:')  
print(a[...,1]) 
print('\n')  

# slice semua item dari baris kedua 
print('Item dari baris kedua:') 
print(a[1,...]) 
print('\n')  

# kita akan slice item dari kolom 1 dan seterusnya
print('item dari kolom 1 dan seterusnya:') 
print(a[...,1:])


Array kita:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


item dari kolom kedua:
[2 4 5]


Item dari baris kedua:
[3 4 5]


item dari kolom 1 dan seterusnya:
[[2 3]
 [4 5]
 [5 6]]


Study Case 
1. Buat array 2 dimensi dengan shape=(3,4)
2. Index dengan mengambil item dari baris kedua dan seterusnya sampai bariss terakhir
3. Index dengan mengambil item dari kolom 1 dan 2

In [9]:
#isi di bagian sini

## Advance Indexing

### Integer Indexing

In [10]:
#contoh 1 mengakses element dari array dua dimensi dengan menentukan baris dan kolom yang disalin
x = np.array([[1, 2], 
              [3, 4], 
              [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


In [11]:
#contoh 2 mengakses element dari array dua dimensi dengan menentukan baris dan kolom yang disalin
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]]) 
   
print('array asli:') 
print(x) 
print('\n') 

rows = np.array([[0,0],[3,3]]) #Baris pertama dan keempat
cols = np.array([[0,2],[0,2]]) #Kolom pertama dan ketiga
y = x[rows,cols] 
   
print('Hasil dari index integer:') 
print(y)

array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Hasil dari index integer:
[[ 0  2]
 [ 9 11]]


In [12]:
#contoh 3
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]]) 

print('Array asli:')
print(x) 
print('\n')  

# slicing 
z = x[1:4,1:3] 

print('setelah, hasil array menjadi:') 
print(z) 
print('\n')  

# using advanced index for column 
y = x[1:4,[1,2]] 

print('slicing dengan advance index untuk column:') 
print(y)

Array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


setelah, hasil array menjadi:
[[ 4  5]
 [ 7  8]
 [10 11]]


slicing dengan advance index untuk column:
[[ 4  5]
 [ 7  8]
 [10 11]]


### Boolean Indexing

In [13]:
#contoh mengambil elemen dengan index boolean (kondisi)
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]]) 

print('Array asli:') 
print(x) 
print('\n')  

# Now we will print the items greater than 5 
print('Item yang lebih besar dari 5:') 
print(x[x > 5])

Array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Item yang lebih besar dari 5:
[ 6  7  8  9 10 11]


In [14]:
#contoh 2
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a[np.isnan(a)])

[nan nan]


In [15]:
#contoh 3
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[~np.iscomplex(a)])

[1.+0.j 5.+0.j]


Study Case 
1. Buat array 2 dimensi dengan shape=(3,4) yang
  isinya campuran antara complex, nan dan integer
2. Ambil item dengan menggunakan index boolean khusus integer, nan dan complex

In [16]:
# isi disini

# Array Manipulation

## Mengubah Shape

### reshape

In [17]:
a = np.arange(8)
print('Array asli:')
print(a)
print('\n')

b = a.reshape(4,2)
print('Array yang telah di modifikasi:')
print(b)


Array asli:
[0 1 2 3 4 5 6 7]


Array yang telah di modifikasi:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### Flatten

In [18]:
a = np.arange(8).reshape(2,4) #take copy

print('Array asli:')
print(a) 
print('\n')  


print('Array yang telah di flattened:') 
print(a.flatten()) 
print('\n')  

print('flattened array dalam F-style ordering:')
print(a.flatten(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


Array yang telah di flattened:
[0 1 2 3 4 5 6 7]


flattened array dalam F-style ordering:
[0 4 1 5 2 6 3 7]


### Ravel

In [19]:
a = np.arange(8).reshape(2,4) # only view

print('Array asli:') 
print(a) 
print('\n')  

print('hasil dari fungsi ravel:') 
print(a.ravel())  
print('\n') 

print('menggunakan ravel function dalam F-style ordering:')
print(a.ravel(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


hasil dari fungsi ravel:
[0 1 2 3 4 5 6 7]


menggunakan ravel function dalam F-style ordering:
[0 4 1 5 2 6 3 7]


## Operasi Transpos

In [20]:
a = np.arange(12).reshape(3,4) 

print('Array asli:') 
print(a)  
print('\n') 

print('Array yang telah di transpos:') 
print(np.transpose(a)) #parameter dengan list int, sesuai dengan dimensi. Secara default, dimensi dibalik
print('\n') 

print('Array yang telah di transpos dengan .T:') 
print(a.T)

Array asli:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array yang telah di transpos:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Array yang telah di transpos dengan .T:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Penggabungan array

### concatenate

In [21]:
a = np.array([[1,2],[3,4]]) 

print('Array Pertama:')
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Array Kedua:') 
print(b) 
print('\n')  
# both the arrays are of same dimensions 

print('gabungan dua array di sumbu 0:') 
print(np.concatenate((a,b)) )
print('\n') 

print('gabungan dua array di sumbu 1:') 
print(np.concatenate((a,b),axis = 1))

Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


gabungan dua array di sumbu 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


gabungan dua array di sumbu 1:
[[1 2 5 6]
 [3 4 7 8]]


### stack

In [22]:
a = np.array([[1,2],[3,4]]) 

print('Array Pertama:') 
print(a) 
print('\n')
b = np.array([[5,6],[7,8]]) 

print('Array kedua:') 
print(b) 
print('\n')  

print('Stack dua array pada sumbu 0:') 
print(np.stack((a,b),0) )
print('\n')  

print('Stack dua array pada sumbu 1:') 
print(np.stack((a,b),1))

Array Pertama:
[[1 2]
 [3 4]]


Array kedua:
[[5 6]
 [7 8]]


Stack dua array pada sumbu 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack dua array pada sumbu 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### hstack

In [23]:
a = np.array([[1,2],[3,4]]) 

print('Array Pertama:') 
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Array Kedua:') 
print(b) 
print('\n')  

print('Horizontal stacking:') 
c = np.hstack((a,b)) 
print(c) 
print('\n')



Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]




### vstack

In [24]:
a = np.array([[1,2],[3,4]]) 

print('Array pertama:') 
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Array kedua:') 
print(b) 
print('\n')

print('Vertical stacking:') 
c = np.vstack((a,b)) 
print(c)


Array pertama:
[[1 2]
 [3 4]]


Array kedua:
[[5 6]
 [7 8]]


Vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Splitting Array (Pemisahan Array) menjadi sub-array

### split

In [25]:
a = np.arange(9)  

print('Array pertama:') 
print(a) 
print('\n')  

print('split array menjadi 3 sub-array yang setara:') 
b = np.split(a,3) 
print(b) 
print('\n')  

print('split berdasarkan index pada array 1 dimensi:') 
b = np.split(a,[4,5]) # numpy.split(ary, indices_or_sections, axis) 
# parameter indicec_or_section dapat berupa bilangan bulat, 
#yang menunjukkan jumlah subarray berukuran sama yang akan dibuat dari array input.
print(b) 


Array pertama:
[0 1 2 3 4 5 6 7 8]


split array menjadi 3 sub-array yang setara:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


split berdasarkan index pada array 1 dimensi:
[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]


### hsplit

In [26]:
a = np.arange(16).reshape(4,4) 

print('Array pertama:') 
print(a) 
print('\n')  

print('Horizontal splitting:') # column wise
b = np.hsplit(a,2) 
print(b) 
print('\n')


Array pertama:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]




### vsplit

In [27]:
a = np.arange(16).reshape(4,4) 

print('Array awal:') 
print(a) 
print('\n')

print('Vertical splitting:') 
b = np.vsplit(a,2) 
print(b)


Array awal:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## Mengubah Element Array (Add/Remove)

In [28]:
# Resize
a = np.array([[1,2,3],
              [4,5,6]]) 

print('Array awal:') 
print(a) 
print('\n')

print('shape array pertama:') 
print(a.shape) 
print('\n')  
b = np.resize(a, (3,2)) 

print('Array kedua:') 
print(b) 
print('\n')  

print('shape array kedua:') 
print(b.shape) 
print('\n')  
# Observe that first row of a is repeated in b since size is bigger 

print('resize array kedua:') 
b = np.resize(a,(3,3)) 
print(b)


Array awal:
[[1 2 3]
 [4 5 6]]


shape array pertama:
(2, 3)


Array kedua:
[[1 2]
 [3 4]
 [5 6]]


shape array kedua:
(3, 2)


resize array kedua:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [29]:
# Append
print('Array Awal')
print(a)
print('\n')

print('Append elements to array:') 
print(np.append(a, [7,8,9])) 
print('\n')  

print('Append elements along axis 0:') 
print(np.append(a, [[7,8,9]],axis = 0)) 
print('\n')  

print('Append elements along axis 1:') 
print(np.append(a, [[5,5,5],[7,8,9]],axis = 1))


Array Awal
[[1 2 3]
 [4 5 6]]


Append elements to array:
[1 2 3 4 5 6 7 8 9]


Append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Append elements along axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [30]:
# Insert 
a = np.array([[1,2],
              [3,4],
              [5,6]]) 

print('Array pertama:') 
print(a) 
print('\n')  

print('tanpa parameter axis. sebelum insertion arraynya di flattened.')
print(np.insert(a,3,[11,12])) 
print('\n')  
print('Menggunakan parameter axis. value arraynya di broadcasr untuk menyamakan input.')

print('Broadcast sepanjang axis 0:') 
print(np.insert(a,1,[11],axis = 0)) 
print('\n')  

print('Broadcast sepanjanhg axis 1:') 
print(np.insert(a,1,11,axis = 1))


Array pertama:
[[1 2]
 [3 4]
 [5 6]]


tanpa parameter axis. sebelum insertion arraynya di flattened.
[ 1  2  3 11 12  4  5  6]


Menggunakan parameter axis. value arraynya di broadcasr untuk menyamakan input.
Broadcast sepanjang axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Broadcast sepanjanhg axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [31]:
# delete
a = np.arange(12).reshape(3,4) 

print('First array:') 
print(a) 
print('\n')  

print('tanpa parameter axis maka di flattened sebelum didelete:') 
print(np.delete(a,5)) 
print('\n')  

print('kolom 2 deleted:')  
print(np.delete(a,1,axis = 1)) 
print('\n')


First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


tanpa parameter axis maka di flattened sebelum didelete:
[ 0  1  2  3  4  6  7  8  9 10 11]


kolom 2 deleted:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




In [32]:
#unique element
a = np.array([5,2,6,2,7,5,6,8,2,9]) 

print('Array pertama:') 
print(a) 
print('\n')  

print('value unik dari array pertama:') 
u = np.unique(a) 
print(u) 
print('\n')  

print('index array:') 
u,indices = np.unique(a, return_index = True) 
print(indices) 
print('\n')


Array pertama:
[5 2 6 2 7 5 6 8 2 9]


value unik dari array pertama:
[2 5 6 7 8 9]


index array:
[1 0 2 4 7 9]




#Broadcasting array

In [33]:
# Contoh 1
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


In [34]:
#contoh 2
a = np.array([[0.0,0.0,0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('Array pertama:') 
print(a) 
print('\n')  
   
print('Array kedua:') 
print(b) 
print('\n')  
   
print('Array pertama + Array kedua') 
print(a + b)


Array pertama:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Array kedua:
[1. 2. 3.]


Array pertama + Array kedua
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


Study Case !
1. Buat dua array yang memiliki shape=(3,4) dan shape (1,4)
2. Lakukan operasi perkalian dan pengurangan 

In [35]:
#isi disini

# Array Iteration

In [36]:
#contoh 1
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array asli:')
print(a)
print('\n')

print('Array yang telah di modifikasi:')
for x in np.nditer(a):
   print(x, end=' ')


Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array yang telah di modifikasi:
0 5 10 15 20 25 30 35 40 45 50 55 

In [37]:
#Urutan iterasi dipilih agar sesuai dengan tata letak memori array, tanpa mempertimbangkan urutan tertentu. 
#Ini dapat dilihat dengan mengulangi transpos dari array di atas.
#contoh 2
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
   
print('Array asli:')
print(a) 
print('\n')  
   
print('Array yang di transpose:') 
b = a.T 
print(b) 
print('\n')  
   
print('Array yang telah di modifikasi:') 
for x in np.nditer(b): 
   print(x, end=' ')



Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array yang di transpose:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Array yang telah di modifikasi:
0 5 10 15 20 25 30 35 40 45 50 55 

Iteration Order

In [38]:
#contoh 3
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Array asli:')
print(a)
print('\n')

print('Transpos array asli:')
b = a.T
print(b)
print('\n')

print('urutkan dalam C-style order:')
c = b.copy(order = 'C')
print(c)
for x in np.nditer(c):
   print(x, end=' ')

print('\n')

print('urutkan dalam F-style order:')
c = b.copy(order = 'F')
print(c)
for x in np.nditer(c):
   print(x, end=' ')


Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpos array asli:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


urutkan dalam C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 20 40 5 25 45 10 30 50 15 35 55 

urutkan dalam F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

In [39]:
#contoh 4
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print('Array asli:') 
print(a) 
print('\n')  

print('Diurutkan dalam C-style order:') 
for x in np.nditer(a, order = 'C'): 
   print(x, end=' ')  
print('\n') 

print('Diurutkan dalam in F-style order:') 
for x in np.nditer(a, order = 'F'): 
   print(x, end=' ')



Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Diurutkan dalam C-style order:
0 5 10 15 20 25 30 35 40 45 50 55 

Diurutkan dalam in F-style order:
0 20 40 5 25 45 10 30 50 15 35 55 

modifikasi nilai elemen array

In [40]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Array asli:')
print(a)
print('\n')

for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print('Array yang telah dimodifikasi:')
print(a)


Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array yang telah dimodifikasi:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


eksternal loop

In [41]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print('Array asli:') 
print(a) 
print('\n')  

print('Array yang telah di modifikasi:') 
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
   print(x, end=' ')


Array asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array yang telah di modifikasi:
[ 0 20 40] [ 5 25 45] [10 30 50] [15 35 55] 

broadcasting iterasi array

In [42]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print('Array pertama:') 
print(a) 
print('\n')  

print('Array kedua:') 
b = np.array([1, 2, 3, 4], dtype = int) 
print(b)  
print('\n') 

print('Array yang telah di modifikasi:') 
for x,y in np.nditer([a,b]): 
   print("%d:%d" % (x,y), end=' ')


Array pertama:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array kedua:
[1 2 3 4]


Array yang telah di modifikasi:
0:1 5:2 10:3 15:4 20:1 25:2 30:3 35:4 40:1 45:2 50:3 55:4 

#Numpy for Mathematics

Fungsi Trigonomeri


NumPy memiliki fungsi trigonometri standar yang mengembalikan rasio trigonometri untuk sudut tertentu dalam radian.

In [43]:
a = np.array([0,30,45,60,90]) 

print('Nilai sin dari sudut yang berbeda-beda:') 
# konversi radian dengan mengalikannya dengan pi/180 
print(np.sin(a*np.pi/180)) 
print('\n')  

print('Nilai kosinus sudut dalam array:') 
print(np.cos(a*np.pi/180)) 
print('\n')  

print('Nilai tangent sudut dalam array:') 
print(np.tan(a*np.pi/180)) 


Nilai sin dari sudut yang berbeda-beda:
[0.         0.5        0.70710678 0.8660254  1.        ]


Nilai kosinus sudut dalam array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Nilai tangent sudut dalam array:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [44]:
a = np.array([0,30,45,60,90]) 

print('Array dengan nilai sinus:') 
sin = np.sin(a*np.pi/180) 
print(sin) 
print('\n')  

print('Hitung inverse(kebalikan) sinus dari sudut. Nilai yang dikembalikan dalam radian.') 
inv = np.arcsin(sin) 
print(inv) 
print('\n')  

print('Periksa hasil dengan mengonversi ke derajat:') 
print(np.degrees(inv)) 
print('\n')  

print('fungsi arccos dan arctan berperilaku serupa:') 
cos = np.cos(a*np.pi/180) 
print(cos) 
print('\n')  

print('Inverse dari cos:') 
inv = np.arccos(cos) 
print(inv) 
print('\n')  

print('dalam derajat:') 
print(np.degrees(inv)) 
print('\n')  

print('Fungsi Tan:') 
tan = np.tan(a*np.pi/180) 
print(tan)
print('\n')  

print('Inverse dari tan:') 
inv = np.arctan(tan) 
print(inv) 
print('\n')  

print('dalam derajat:') 
print(np.degrees(inv))


Array dengan nilai sinus:
[0.         0.5        0.70710678 0.8660254  1.        ]


Hitung inverse(kebalikan) sinus dari sudut. Nilai yang dikembalikan dalam radian.
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


Periksa hasil dengan mengonversi ke derajat:
[ 0. 30. 45. 60. 90.]


fungsi arccos dan arctan berperilaku serupa:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Inverse dari cos:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


dalam derajat:
[ 0. 30. 45. 60. 90.]


Fungsi Tan:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Inverse dari tan:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


dalam derajat:
[ 0. 30. 45. 60. 90.]


Fungsi Pembulatan dengan numpy.round


numpy.around(a,decimals)

In [45]:
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print('Array asli:') 
print(a) 
print('\n')  

print('Setelah pembulatan:') 
print(np.around(a)) 
print(np.around(a, decimals = 1)) 


Array asli:
[  1.      5.55  123.      0.567  25.532]


Setelah pembulatan:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]


np.floor


Fungsi ini mengembalikan bilangan bulat terbesar yang tidak lebih besar dari parameter input. Dasar skalar x adalah bilangan bulat terbesar i, sehingga i <= x. Perhatikan bahwa dalam Python, floor selalu dibulatkan dari 0.

In [46]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print('Array asli:') 
print(a) 
print('\n')  

print('flooring array:') 
print(np.floor(a))


Array asli:
[-1.7  1.5 -0.2  0.6 10. ]


flooring array:
[-2.  1. -1.  0. 10.]


np.ceil

Fungsi ceil() mengembalikan plafon nilai input, yaitu ceil skalar x adalah bilangan bulat terkecil i, sehingga i >= x.

In [47]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print('Array asli:') 
print(a) 
print('\n')  

print('ceiling array:') 
print(np.ceil(a))


Array asli:
[-1.7  1.5 -0.2  0.6 10. ]


ceiling array:
[-1.  2. -0.  1. 10.]


## Operasi Aritmatika

Di dalam numpy ada fungsi untuk melakukan penjumlahan, pengurangan, perkalian dan pembagian

In [48]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('Array pertama:') 
print(a) 
print('\n')  

print('Array kedua:') 
b = np.array([10,10,10]) 
print(b) 
print('\n')  

print('Penjumlahan 2 array:') 
print(np.add(a,b)) 
print('\n')  

print('Pengurangan 2 array:') 
print(np.subtract(a,b)) 
print('\n')  

print('Perkalian 2 array:') 
print(np.multiply(a,b)) 
print('\n')  

print('Pembagian 2 array:') 
print(np.divide(a,b))


AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

Operasi perkalian pangkat dengan numpy.power

In [59]:
a = np.array([10,100,1000]) 

print('Array asli:') 
print(a) 
print('\n')  

print('Menggunakan power function:') 
print(np.power(a,2)) 
print('\n')  

print('Array kedua:') 
b = np.array([1,2,3]) 
print(b) 
print('\n')  

print('Menggunakan power function lagi:') 
print(np.power(a,b))


Array asli:
[  10  100 1000]


Menggunakan power function:
[    100   10000 1000000]


Array kedua:
[1 2 3]


Menggunakan power function lagi:
[        10      10000 1000000000]


Mengambil nilai sisa hasil bagi dengan np.mod/np.remainder

In [60]:
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 

print('Array pertama:') 
print(a) 
print('\n')  

print('Array kedua:') 
print(b) 
print('\n')  

print('menggunakan mod() function:') 
print(np.mod(a,b)) 
print('\n')  

print('menggunakan remainder() function:') 
print(np.remainder(a,b)) 


Array pertama:
[10 20 30]


Array kedua:
[3 5 7]


menggunakan mod() function:
[1 0 2]


menggunakan remainder() function:
[1 0 2]


## Fungsi Statistika

In [65]:
# Mencari nilai minimum dan maximum dalam suatu array
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print('Array asli:') 
print(a)  
print('\n')  

print('menggunakan amin() function:') 
print(np.amin(a,1)) 
print('\n')  

print('menggunakan amin() function lagi:') 
print(np.amin(a,0)) 
print('\n')  

print('menggunakan amax() function:') 
print(np.amax(a)) 
print('\n')  

print('menggunakan amax() function lagi:') 
print(np.amax(a, axis = 0))


Array asli:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


menggunakan amin() function:
[3 3 2]


menggunakan amin() function lagi:
[2 4 3]


menggunakan amax() function:
9


menggunakan amax() function lagi:
[8 7 9]


np.percentile

Persentil (atau satu persentil) adalah ukuran yang digunakan dalam statistik yang menunjukkan nilai di bawah persentase pengamatan tertentu dalam kelompok pengamatan.


numpy.percentile(a, q, axis)


a : Input array

q : Persentil yang akan dihitung harus antara 0-100

axis : sumbu

Persentil untuk nilai dalam kumpulan data tertentu dapat dihitung menggunakan rumus:

n = (P/100) x N


di mana N = jumlah nilai dalam kumpulan data, P = persentil, dan n = peringkat ordinal dari nilai yang diberikan (dengan nilai dalam kumpulan data diurutkan dari terkecil ke terbesar). Misalnya, ambil kelas yang terdiri dari 20 siswa yang memperoleh nilai berikut pada tes terbaru mereka: 75, 77, 78, 78, 80, 81, 81, 82, 83, 84, 84, 84, 85, 87, 87, 88, 88, 88, 89, 90. Skor ini dapat direpresentasikan sebagai kumpulan data dengan 20 nilai: {75, 77, 78, 78, 80, 81, 81, 82, 83, 84, 84, 84, 85, 87, 87, 88, 88, 88, 89, 90}.

Kita dapat menemukan skor yang menandai persentil ke-20 dengan memasukkan nilai yang diketahui ke dalam rumus dan menyelesaikan n:

n = (20/100) x 20

n = 4

Nilai keempat dalam kumpulan data adalah skor 78. Ini berarti bahwa 78 menandai persentil ke-20; dari siswa di kelas, 20 persen memperoleh skor 78 atau lebih rendah.

In [134]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print('Array asli:') 
print(a) 
print('\n')  

print('menggunakan percentile() function:') 
print(np.percentile(a,50)) 
print('\n')  

print('Menggunakan percentile() function disumbu 1:') 
print(np.percentile(a,50, axis = 1)) 
print('\n')  

print('Menggunakan percentile() function disumbu 0:') 
print(np.percentile(a,50, axis = 0))




Array asli:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


menggunakan percentile() function:
50.0


Menggunakan percentile() function disumbu 1:
[40. 20. 60.]


Menggunakan percentile() function disumbu 0:
[50. 40. 60.]


Median didefinisikan sebagai nilai yang memisahkan bagian yang lebih tinggi dari sampel data dari bagian yang lebih rendah, dan bisa di hitung menggunakan numpy.median

In [69]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print('Array asli:') 
print(a) 
print('\n')  

print('menggunakan median() function:') 
print(np.median(a)) 
print('\n')  

print('menggunakan median() function sepanjang sumbu 0:') 
print(np.median(a, axis = 0)) 
print('\n')  
 
print('Menggunakan median() function sepanjang axis 1:') 
print(np.median(a, axis = 1))


Array asli:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


menggunakan median() function:
65.0


menggunakan median() function sepanjang sumbu 0:
[50. 90. 60.]


Menggunakan median() function sepanjang axis 1:
[65. 80. 60.]


Rata-rata aritmatika adalah jumlah elemen sepanjang sumbu dibagi dengan jumlah elemen. Fungsi numpy.mean() mengembalikan mean aritmatika elemen dalam array. Jika sumbu disebutkan secara eksplisit, maka akan dihitung berdasarkan nilai sumbunya




In [70]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Array asli:') 
print(a) 
print('\n')  

print('Menggunakan mean() function:') 
print(np.mean(a)) 
print('\n')  

print('Menggunakan mean() function sepanjang sumbu 0:') 
print(np.mean(a, axis = 0)) 
print('\n')  

print('Menggunakan mean() function sepanjang sumbu 1:') 
print(np.mean(a, axis = 1))


Array asli:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Menggunakan mean() function:
3.6666666666666665


Menggunakan mean() function sepanjang sumbu 0:
[2.66666667 3.66666667 4.66666667]


Menggunakan mean() function sepanjang sumbu 1:
[2. 4. 5.]


Rata-rata tertimbang adalah rata-rata yang dihasilkan dari perkalian setiap komponen dengan faktor yang mencerminkan kepentingannya. Fungsi numpy.average() menghitung rata-rata tertimbang elemen dalam array sesuai dengan bobot masing-masing yang diberikan dalam array lain. Fungsi dapat memiliki parameter sumbu. Jika sumbu tidak ditentukan, array diratakan.

Mempertimbangkan array [1,2,3,4] dan bobot yang sesuai [4,3,2,1], rata-rata tertimbang dihitung dengan menambahkan produk dari elemen yang sesuai dan membagi jumlah dengan jumlah bobot.

Rata-rata tertimbang = (1*4+2*3+3*2+4*1)/(4+3+2+1)

In [71]:
a = np.array([1,2,3,4]) 

print('Array asli:') 
print(a) 
print('\n')  

print('menggunakan average() function:') 
print(np.average(a)) 
print('\n')  

# this is same as mean when weight is not specified 
wts = np.array([4,3,2,1]) 

print('menggunakan average() function lagi:') 
print(np.average(a,weights = wts)) 
print('\n')  

# Returns the sum of weights, if the returned parameter is set to True. 
print('Sum of weights') 
print(np.average([1,2,3, 4],weights = [4,3,2,1], returned = True))


Array asli:
[1 2 3 4]


menggunakan average() function:
2.5


menggunakan average() function lagi:
2.0


Sum of weights
(2.0, 10.0)


Standar deviasi  adalah ukuran seberapa tersebar data dalam kaitannya dengan mean. Standar deviasi rendah berarti data mengelompok di sekitar rata-rata, dan standar deviasi tinggi menunjukkan data lebih tersebar.

In [77]:
np.std([1,2,3,4])

1.118033988749895

Varians adalah ukuran variabilitas. Ini dihitung dengan mengambil rata-rata deviasi kuadrat dari mean. Varians memberi tahu Anda tingkat penyebaran dalam kumpulan data Anda. Semakin menyebar data, semakin besar varians dalam kaitannya dengan mean

In [135]:
print(np.var([1,2,3,4]))

1.25


Standar deviasi mengukur seberapa jauh angka-angka dalam kumpulan data. Varians, di sisi lain, memberikan nilai aktual seberapa banyak angka dalam kumpulan data bervariasi dari rata-rata